# Generated by Django 5.1.6 on 2025-02-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_no', models.CharField(max_length=100)),
                ('quarter', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('cpu_make_model', models.CharField(max_length=255)),
                ('serial_no', models.CharField(max_length=255)),
                ('computer_name', models.CharField(max_length=255)),
                ('employee_code', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('system_model', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
                ('monitor_serial_no', models.CharField(max_length=255)),
                ('mouse_serial_no', models.CharField(max_length=255)),
                ('keyboard_serial_no', models.CharField(max_length=255)),
                ('activities', models.TextField()),
            ],
        ),
    ]
