# Generated by Django 5.1.6 on 2025-02-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_maintenancereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancereport',
            old_name='employee_code',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='maintenancereport',
            old_name='location_name',
            new_name='employee_name',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='activities',
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='employee_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
