# Generated by Django 5.1.6 on 2025-02-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_maintenancereport_computer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancereport',
            old_name='keyboard_serial_no',
            new_name='adobe_reader_version',
        ),
        migrations.RenameField(
            model_name='maintenancereport',
            old_name='monitor_serial_no',
            new_name='chrome_version',
        ),
        migrations.RenameField(
            model_name='maintenancereport',
            old_name='mouse_serial_no',
            new_name='hdd_info',
        ),
        migrations.RenameField(
            model_name='maintenancereport',
            old_name='serial_no',
            new_name='java_version',
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='keyboard_serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='monitor_serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='mouse_serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='processor_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='ram_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='sap_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='ultravnc_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
