# Generated by Django 5.1.6 on 2025-02-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_maintenancereport_dsc_driver_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancereport',
            old_name='ms_office_veraion',
            new_name='ms_office_version',
        ),
    ]
