# Generated by Django 5.1.6 on 2025-02-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_rename_ms_office_veraion_maintenancereport_ms_office_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='indic_tool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
