# Generated by Django 5.1.6 on 2025-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_maintenancereport_keyboard_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='trellix_dlp_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='trellix_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
