# Generated by Django 5.1.6 on 2025-02-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_maintenancereport_trellix_dlp_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancereport',
            old_name='department',
            new_name='employee_department',
        ),
        migrations.RenameField(
            model_name='maintenancereport',
            old_name='designation',
            new_name='employee_designation',
        ),
    ]
