# Generated by Django 5.1.6 on 2025-02-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_rename_department_maintenancereport_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
