# Generated by Django 5.1.6 on 2025-02-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_maintenancereport_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='app_installed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='bigfix_control',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='pc_purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='trellix_endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='trellix_threat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
