# Generated by Django 5.1.6 on 2025-02-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_maintenancereport_app_installed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_1_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_1_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_2_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_2_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_3_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_3_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_4_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_4_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_5_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_5_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_6_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_6_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_7_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='activity_7_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
