# Generated by Django 5.1.6 on 2025-02-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_maintenancereport_activity_1_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancereport',
            name='activity_7_details',
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='activity_7_status',
        ),
    ]
