# Generated by Django 5.1.6 on 2025-02-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_remove_maintenancereport_activity_7_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='floor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='location_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='sro_tnso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
