# Generated by Django 5.1.6 on 2025-02-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_maintenancereport_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='printer_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='printer_serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='printer_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='printer_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
