# Generated by Django 5.1.6 on 2025-02-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_maintenancereport_printer_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereport',
            name='activity_1_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='activity_2_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='activity_3_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='activity_4_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='activity_5_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='activity_6_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
