# Generated by Django 5.1.6 on 2025-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0021_remove_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
