# Generated by Django 5.1.6 on 2025-02-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
