# Generated by Django 5.1.6 on 2025-02-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_maintenancereport_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancereport',
            name='created_at',
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='created_at_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
