# Generated by Django 5.1.6 on 2025-02-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0024_remove_maintenancereport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
