# Generated by Django 5.1.6 on 2025-02-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0026_set_default_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
