# Generated by Django 5.1.6 on 2025-02-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_employee_location_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancereport',
            options={'ordering': ['pm_no', 'quarter', 'year', 'date', 'created_at_time', 'employee_number', 'employee_name', 'employee_department', 'employee_designation', 'sro_tnso', 'floor', 'location_name', 'ip_address', 'cpu_make_model', 'serial_number', 'computer_name', 'monitor_serial_number', 'system_model', 'os_version', 'keyboard_type', 'keyboard_serial_number', 'mouse_type', 'mouse_serial_number', 'processor_type', 'hdd_info', 'ram_info', 'sap_version', 'java_version', 'ultravnc_version', 'adobe_reader_version', 'chrome_version', 'os_patch', 'laps_version', 'dsc_driver_version', 'ms_office_version', 'indic_tool', 'trellix_version', 'trellix_dlp_version', 'trellix_endpoint', 'trellix_threat', 'bigfix_control', 'printer_model', 'printer_serial_number', 'printer_type', 'printer_status', 'printer_remark', 'activity_1_status', 'activity_1_details', 'activity_2_status', 'activity_2_details', 'activity_3_status', 'activity_3_details', 'activity_4_status', 'activity_4_details', 'activity_5_status', 'activity_5_details', 'activity_6_status', 'activity_6_details', 'pc_purpose', 'app_installed']},
        ),
    ]
