# Generated by Django 5.1.6 on 2025-02-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_alter_maintenancereport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancereport',
            options={},
        ),
        migrations.RemoveField(
            model_name='maintenancereport',
            name='ultravnc_version',
        ),
    ]
